# Generated by Django 3.2.9 on 2022-07-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('audio', models.FileField(upload_to='media/audios/', verbose_name='audio')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('number_of_leaks', models.PositiveIntegerField(default=0, verbose_name='number_of_leaks')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('votes',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('file', models.FileField(upload_to='media/files/', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='media/images/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500, verbose_name='reply')),
                ('votes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'replies',
                'ordering': ('votes',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('video', models.FileField(upload_to='media/videos/', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='header')),
                ('text', models.TextField(blank=True, max_length=30000, null=True, verbose_name='text')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('audios', models.ManyToManyField(blank=True, related_name='audios', to='leak.Audio')),
                ('files', models.ManyToManyField(blank=True, related_name='files', to='leak.File')),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='leak.Image')),
                ('videos', models.ManyToManyField(blank=True, related_name='videos', to='leak.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Leak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('votes', models.IntegerField(default=0, verbose_name='votes')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='leak.category')),
                ('sections', models.ManyToManyField(blank=True, related_name='sections', to='leak.Section')),
            ],
        ),
    ]
