# Generated by Django 3.2.9 on 2022-07-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='leak',
            name='demographic',
            field=models.CharField(max_length=100, null=True, verbose_name='demographic'),
        ),
    ]
