# Generated by Django 3.2.9 on 2022-07-16 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leak', '0002_auto_20220716_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
