# Generated by Django 3.2.9 on 2022-07-09 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leak', '0003_alter_leak_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='leak',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='leak/audios/', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='category',
            name='number_of_leaks',
            field=models.PositiveIntegerField(default=0, verbose_name='number of leaks'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='leak/files/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='leak/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='leak/videos/', verbose_name='video'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('number_of_leaks', models.PositiveIntegerField(default=0, verbose_name='number of leaks')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leak.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
    ]
