# Generated by Django 3.2.9 on 2022-07-16 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leak', '0004_auto_20220716_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='subcategories_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
