# Generated by Django 3.2.9 on 2022-07-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leak', '0004_auto_20220709_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='leak.Subcategory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replies', to='leak.Reply'),
        ),
        migrations.AddField(
            model_name='leak',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='leak.Comment'),
        ),
    ]
