# Generated by Django 3.2.9 on 2022-07-09 14:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leak', '0005_auto_20220709_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='leak',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='leak',
            name='description',
        ),
        migrations.RemoveField(
            model_name='leak',
            name='sections',
        ),
        migrations.AddField(
            model_name='audio',
            name='leak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_audio', to='leak.leak'),
        ),
        migrations.AddField(
            model_name='comment',
            name='leak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_comment', to='leak.leak'),
        ),
        migrations.AddField(
            model_name='file',
            name='leak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_file', to='leak.leak'),
        ),
        migrations.AddField(
            model_name='image',
            name='leak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_image', to='leak.leak'),
        ),
        migrations.AddField(
            model_name='leak',
            name='story',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='story'),
        ),
        migrations.AddField(
            model_name='leak',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_subcategory', to='leak.subcategory'),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_comment_reply', to='leak.comment'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='leak.category'),
        ),
        migrations.AddField(
            model_name='video',
            name='leak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_video', to='leak.leak'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='leak',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_category', to='leak.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
