# Generated by Django 3.2.9 on 2022-07-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leak', '0006_auto_20220709_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='title'),
        ),
    ]
