# Generated by Django 3.2.9 on 2022-07-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leak', '0008_subcategory_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leak',
            name='demographic',
        ),
    ]
