# Generated by Django 3.2.9 on 2022-07-11 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leak', '0007_alter_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audios', models.ManyToManyField(blank=True, related_name='archives', to='leak.Audio')),
                ('files', models.ManyToManyField(blank=True, related_name='archives', to='leak.File')),
                ('images', models.ManyToManyField(blank=True, related_name='archives', to='leak.Image')),
                ('leaks', models.ManyToManyField(blank=True, related_name='archives', to='leak.Leak')),
                ('user', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='archives', to='leak.Video')),
            ],
        ),
    ]
