# Generated by Django 3.2.9 on 2022-07-11 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leak', '0007_alter_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='genz/profile_picture/', verbose_name='Picture')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Biography')),
                ('gender', models.CharField(blank=True, choices=[('le', 'male'), ('fele', 'female')], max_length=10, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('state_of_residence', models.CharField(blank=True, max_length=100, null=True, verbose_name='state Of Residence')),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='State Of Origin')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationlity')),
                ('language1', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Language')),
                ('language2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Second Language')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('subcategories', models.ManyToManyField(blank=True, related_name='profileSubcategories', to='leak.Subcategory')),
                ('user', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
