# Generated by Django 3.2.9 on 2022-07-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subcategories',
        ),
    ]
